In [43]:
import pandas as pd
import numpy as np

## 예제 8-1 난수 생성 이해하기
### 전역난수 생성 vs 지역 난수 생성

### 난수를 발생해 본다

In [44]:
# randn(n)함수는 표준편차가 1이고 평균이 0인 랜덤한 소수를 n개 발생시킨다.
np.random.randn(5)

array([-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471, -0.57860025])

In [45]:
np.random.randn(5)

array([ 1.65143654, -2.42667924, -0.42891263,  1.26593626, -0.8667404 ])

In [46]:
np.random.randn(5)

array([-0.67888615, -0.09470897,  1.49138963, -0.638902  , -0.44398196])

In [47]:
np.random.randn(5)

array([-0.43435128,  2.20593008,  2.18678609,  1.0040539 ,  0.3861864 ])

### 난수를 생성할 때마다 값은 임의로 발생한다.
난수 발생한 순소를 재현하려면 모든 발생값을 저장해야만 한다.

### seed를 통해 무작위성을 통제해보기

In [48]:
np.random.seed(123)
np.random.randn(5)

array([-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471, -0.57860025])

In [49]:
np.random.randn(5)

array([ 1.65143654, -2.42667924, -0.42891263,  1.26593626, -0.8667404 ])

In [50]:
# 다시 seed값을 설정하고 난수 발생시, 동일한 결과로 난수가 발생한다.
np.random.seed(123)
np.random.randn(5)

array([-1.0856306 ,  0.99734545,  0.2829785 , -1.50629471, -0.57860025])

In [51]:
np.random.randn(5)

array([ 1.65143654, -2.42667924, -0.42891263,  1.26593626, -0.8667404 ])

### 전역 난수방식의 문제는 향후 발생하는 모든 난수는 시드의 영향을 받게 된다는 점이다.
따라서 독립적인 난수를 발생시키고 싶을 경우 지역 난수를 사용한다.

In [52]:
# RandomState(n)함수는 지역 난수를 생성한다. n은 시드번호.
rns = np.random.RandomState(456)
rns.randn(5)

array([-0.6681285 , -0.49820952,  0.61857582,  0.56869225,  1.35050948])

In [53]:
rns.randn(5)

array([ 1.62958853,  0.30196621,  0.44948318, -0.34581112, -0.31523083])

In [54]:
np.random.seed(123)
rns = np.random.RandomState(456)
rns.randn(5)

array([-0.6681285 , -0.49820952,  0.61857582,  0.56869225,  1.35050948])

In [55]:
rns.randn(5)

array([ 1.62958853,  0.30196621,  0.44948318, -0.34581112, -0.31523083])

# 예제 8-2 데이터프레임 브로드캐스팅 기타 응용

In [56]:
rng = np.random.RandomState(42)
df_2 = pd.DataFrame((rng.randint(0, 20, (4, 4))), columns=list('QRST'))
df_2

Q   R   S   T
0   6  19  14  10
1   7   6  18  10
2  10   3   7   2
3   1  11   5   1

In [57]:
df_2.iloc[0]

Q     6
R    19
S    14
T    10
Name: 0, dtype: int32

In [58]:
# 데이터프레임의 행마다 조건 행을 뺄셈한다.
df_2 - df_2.iloc[0]

Q   R  S  T
0  0   0  0  0
1  1 -13  4  0
2  4 -16 -7 -8
3 -5  -8 -9 -9

In [59]:
# subtract(행,axis = 1)함수는 데이터프레임의 모든 행에 행단위 뺄셈연산을 한다.
# 열을 고정하여 행단위 연산을 한다는 의미로 axis = 1 로 지정한다.
df_2.subtract(df_2.iloc[0],axis = 1)

Q   R  S  T
0  0   0  0  0
1  1 -13  4  0
2  4 -16 -7 -8
3 -5  -8 -9 -9

In [60]:
# 동일한 요소가 아니면 아무 연산도 일어나지 않고 NaN 처리됨
# 뺄 값 요소는 행, 기준은 열이므로 오류
df_2.subtract(df_2.iloc[0],axis = 0)

Q   R   S   T
0 NaN NaN NaN NaN
1 NaN NaN NaN NaN
2 NaN NaN NaN NaN
3 NaN NaN NaN NaN
Q NaN NaN NaN NaN
R NaN NaN NaN NaN
S NaN NaN NaN NaN
T NaN NaN NaN NaN

In [61]:
df_2['R']

0    19
1     6
2     3
3    11
Name: R, dtype: int32

In [62]:
# 데이터프레임의 브로드캐스팅은 행단위로 이루어져 있으므로 열단위 연산처리는 할 수 없다.
df_2 - df_2['R']

Q   R   S   T   0   1   2   3
0 NaN NaN NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN NaN NaN NaN

In [63]:
# 열단위 연산은 지원되는 메소드를 통해 진행한다.
df_2.subtract(df_2['R'],axis = 0)

Q  R   S   T
0 -13  0  -5  -9
1   1  0  12   4
2   7  0   4  -1
3 -10  0  -6 -10

In [64]:
df_2.subtract(df_2['R'],axis=1)

Q   R   S   T   0   1   2   3
0 NaN NaN NaN NaN NaN NaN NaN NaN
1 NaN NaN NaN NaN NaN NaN NaN NaN
2 NaN NaN NaN NaN NaN NaN NaN NaN
3 NaN NaN NaN NaN NaN NaN NaN NaN

---

# 예제 8-4 사용자 정의 함수를 apply메서드로 처리하기

In [70]:
df = pd.DataFrame ({'a' : np.random.randn(6),
                 'b' : ['철수', '영희'] * 3,
                 'c' : np.random.randn(6)})

In [71]:
df

a   b         c
0  1.491390  철수  1.004054
1 -0.638902  영희  0.386186
2 -0.443982  철수  0.737369
3 -0.434351  영희  1.490732
4  2.205930  철수 -0.935834
5  2.186786  영희  1.175829

In [74]:
def my_test(a,c):
    return a % c

In [75]:
# lambda 함수는 행단위로 데이터를 처리하는 사용자 함수를 이용한다
df['Value'] = df.apply(lambda df: my_test(df['a'],df['c']), axis = 1)
#                         입력값 : 출력값                  , 축

In [76]:
df

a   b         c     Value
0  1.491390  철수  1.004054  0.487336
1 -0.638902  영희  0.386186  0.133471
2 -0.443982  철수  0.737369  0.293387
3 -0.434351  영희  1.490732  1.056381
4  2.205930  철수 -0.935834 -0.601572
5  2.186786  영희  1.175829  1.010957

In [77]:
# Value열 확인
df.a % df.c

0    0.487336
1    0.133471
2    0.293387
3    1.056381
4   -0.601572
5    1.010957
dtype: float64

In [78]:
# 일반함수는 데이터 프레임 전체를 넘겨 열 전체의 값을 반환하는 형태로 작성한다.
def my_test2(df):
    return df['a'] % df['c']

In [79]:
df['Value2'] = df.apply(my_test2,axis = 1)

In [80]:
df

a   b         c     Value    Value2
0  1.491390  철수  1.004054  0.487336  0.487336
1 -0.638902  영희  0.386186  0.133471  0.133471
2 -0.443982  철수  0.737369  0.293387  0.293387
3 -0.434351  영희  1.490732  1.056381  1.056381
4  2.205930  철수 -0.935834 -0.601572 -0.601572
5  2.186786  영희  1.175829  1.010957  1.010957

In [82]:
%timeit df['Value'] = df.apply(lambda df: my_test(df['a'],df['c']), axis = 1)

611 µs ± 11.2 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [83]:
%timeit df['Value2'] = df.apply(my_test2,axis = 1)

626 µs ± 10.4 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [85]:
sample = pd.DataFrame({'임의의값':[10,100,40]})
sample

임의의값
0    10
1   100
2    40

In [86]:
# 기존의 데이터 3개에 10만을 곱하여 30만개의 데이터를 생성한다.
# 인덱스는 갱신되어야 하므로 reset_index 함수 인자에 drop = True를 하면
# 기존 인덱스를 버리고 새로운 인덱스로 생성된다.
sample = pd.concat([sample]*100000).reset_index(drop = True)

In [87]:
sample.shape

(300000, 1)

In [88]:
sample.head(10)

임의의값
0    10
1   100
2    40
3    10
4   100
5    40
6    10
7   100
8    40
9    10

In [89]:
%timeit sample['임의의값'].apply(lambda x : np.nan if x < 90 else x)

72.9 ms ± 1.05 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [90]:
%timeit sample['임의의값'].mask(sample['임의의값'] < 90 , np.nan)

3.91 ms ± 154 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [91]:
sample1 = sample.copy()

In [92]:
sample1 = sample['임의의값'].apply(lambda x : np.nan if x < 90 else x)

In [94]:
sample1.head()

0      NaN
1    100.0
2      NaN
3      NaN
4    100.0
Name: 임의의값, dtype: float64

In [95]:
sample2 = sample['임의의값'].mask(sample['임의의값'] < 90, np.nan)

In [96]:
sample2.head()

0      NaN
1    100.0
2      NaN
3      NaN
4    100.0
Name: 임의의값, dtype: float64

In [97]:
(sample1 == sample2).shape

(300000,)

In [99]:
sample1.isnull().sum(), sample1.notnull().sum()

(200000, 100000)

In [100]:
(sample1 == sample2).sum()

100000

# 예제 8-5 사용자 정의 함수를 map,applymap메소드로 처리하기

In [102]:
ser = pd.Series(np.random.randn(6))
ser

0   -0.255619
1   -2.798589
2   -1.771533
3   -0.699877
4    0.927462
5   -0.173636
dtype: float64

In [104]:
df = pd.DataFrame(ser,columns=['관측값_A'])
df

관측값_A
0 -0.255619
1 -2.798589
2 -1.771533
3 -0.699877
4  0.927462
5 -0.173636

In [105]:
def map_test(a):
    print('원소별 처리')
    return np.abs(a)

In [106]:
# 열거형객체.map(함수) : 열거형 객체의 각 인수에 함수를 매핑하여 적용한다.
ser.map(map_test)

원소별 처리
원소별 처리
원소별 처리
원소별 처리
원소별 처리
원소별 처리


0    0.255619
1    2.798589
2    1.771533
3    0.699877
4    0.927462
5    0.173636
dtype: float64

In [107]:
s = pd.Series(ser.map(map_test))

원소별 처리
원소별 처리
원소별 처리
원소별 처리
원소별 처리
원소별 처리


In [108]:
s

0    0.255619
1    2.798589
2    1.771533
3    0.699877
4    0.927462
5    0.173636
dtype: float64

In [110]:
df['관측값_1_절대값'] = s
df

관측값_A  관측값_1_절대값
0 -0.255619   0.255619
1 -2.798589   2.798589
2 -1.771533   1.771533
3 -0.699877   0.699877
4  0.927462   0.927462
5 -0.173636   0.173636

# 예제 8-6 pipe 메소드 처리하기

In [111]:
df = pd.DataFrame({"name": ['김상갑', '임종문', '조현웅'],
                   "program language": [np.nan, 'Python', 'Scala'],
                   "born": [pd.NaT, pd.Timestamp("1966-04-25"),
                             pd.NaT]})

In [112]:
df

name program language       born
0  김상갑              NaN        NaT
1  임종문           Python 1966-04-25
2  조현웅            Scala        NaT

In [113]:
def name_length(df):
    df['length'] = df.name.str.len()
    return df
# 사용자 정의 함수 안에서 열을 추가하고 데이터프레임을 리턴한다.

In [114]:
# 판다스에서 pipe라는 함수로도 사용자 정의 함수를 지정할 수 있다.

In [115]:
df.pipe(name_length)

name program language       born  length
0  김상갑              NaN        NaT       3
1  임종문           Python 1966-04-25       3
2  조현웅            Scala        NaT       3

In [117]:
def born_fillna(df):
    df['born'] = df['born'].fillna(pd.Timestamp('1967-04-25'))
    return df

In [118]:
df.pipe(born_fillna)

name program language       born  length
0  김상갑              NaN 1967-04-25       3
1  임종문           Python 1966-04-25       3
2  조현웅            Scala 1967-04-25       3

In [119]:
def pl_fillna(df):
    df['program language'] = df['program language'].fillna('java')
    return df

In [120]:
df.pipe(pl_fillna)

name program language       born  length
0  김상갑             java 1967-04-25       3
1  임종문           Python 1966-04-25       3
2  조현웅            Scala 1967-04-25       3